services:
  proxy:
    image: nginx:proxy_1.80.0
    volumes:
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx-log:/var/log/nginx"
    ports:
      - "18088:18088"
      - "4000:80"
      - "8443:443"
    restart: unless-stopped
